---
- name: build and run java_app on docker
  hosts: build
  become: yes
  tasks:
    - name: update repository
      apt:
       update_cache: yesupdate
    - name: Ensure docker install
      apt:
      name: docker.io
      state: present
    - name: Ensure Dockerfile is clone
      git:
       repo: https://github.com/henre1989/Dockerfile_java_app.git
       dist: /home/server1/
    - name: Ensure build docker image
      docker_image:
       build:
        path: /home/server1//Dockerfile_java_app
       name: henre1989/java_app
       tag: v1
       push: yes
       source: build

