---
- name: build and run java_app on docker
  hosts: build
  become: yes
  tasks:
    - name: update repository
      apt:
       update_cache: yes
    - name: Ensure docker install
      apt:
       name: docker.io
       state: present
    - name: Ensure Dockerfile is clone
      git:
       repo: https://github.com/henre1989/Dockerfile_java_app.git
       dest: /home/server1/Dockerfile_java_app
    - name: Ensure python-pip is install
      apt:
       name: python-pip
       state: present
    - name: Ensure python-docker is install
      pip:
       name: python-docker
       state: present
    - name: Ensure Docker SDK for Python is install
      pip:
       name: docker
       state: present
    - name: Ensure PyYAML is install
      pip:
       name: PyYAML
       state: present
    - name: Ensure build docker image und push to dockerhub
      docker_image:
       build:
        path: /home/server1//Dockerfile_java_app
       #name: henre1989/java_app
       name: java_app
       tag: v1
       #push: yes
       source: build
